name: Lint and Test

on: push

jobs:

  test:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install JS tooling
        run: npm install

      - name: Install PHP tooling
        run: composer install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
